[package]
name = "rdr-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdr-core = { path = "../rdr-core" }
rdr-zeromq = { path = "../rdr-zeromq" }

tokio = { version = "1" }
bytes = "1"
